export const CATEGORIES = [
    { id: 'all',      label: 'الكل',     icon: 'all-icon' },
    { id: 'proverbs', label: 'أمثال',    icon: 'proverbs-icon' },
    { id: 'wisdom',   label: 'حكم',      icon: 'wisdom-icon' },
    { id: 'religion', label: 'إسلامية',  icon: 'religion-icon' },
    { id: 'poetry',   label: 'شعر',      icon: 'poetry-icon' }
];

export const questionsDB = {
    easy: [
        { icons: ["apple", "tree"], answer: "التفاحة لا تسقط بعيداً عن الشجرة", hints: ["مثل عن الوراثة", "يتحدث عن الأبناء والآباء", "التفاحة قريبة من أصلها"], category: "proverbs" },
        { icons: ["bird", "hand"], answer: "عصفور في اليد خير من عشرة على الشجرة", hints: ["عن القناعة", "أفضل من الذي على الشجرة", "مثل شعبي مشهور"], category: "proverbs" },
        { icons: ["water-drop", "rock"], answer: "قطرة الماء تثقب الحجر", hints: ["عن المثابرة", "الصبر يحقق المستحيل", "الماء والصخر"], category: "wisdom" },
        { icons: ["key", "heart"], answer: "القلوب عند بعضها", hints: ["عن التفاهم", "الحب والتواصل", "القلوب متصلة"], category: "proverbs" },
        { icons: ["sunrise", "rooster"], answer: "من بكّر طار", hints: ["عن النشاط الصباحي", "البكور مفيد", "الاستيقاظ المبكر"], category: "proverbs" },
        { icons: ["eye", "eye", "x-mark", "anatomical-heart"], answer: "بعيد عن العين بعيد عن القلب", hints: ["عن البعد والنسيان", "الغياب", "المسافة تؤثر"], category: "proverbs" },
        { icons: ["shush", "gold-medal"], answer: "السكوت من ذهب", hints: ["عن قيمة الصمت", "الكلام فضة", "مثل عن الحكمة"], category: "wisdom" },
        { icons: ["clock", "money-bag"], answer: "الوقت من ذهب", hints: ["عن قيمة الوقت", "لا تضيع وقتك", "الوقت ثمين"], category: "wisdom" },
        { icons: ["books", "sword"], answer: "القلم أقوى من السيف", hints: ["عن قوة العلم", "الكتابة والمعرفة", "العلم قوة"], category: "wisdom" },
        { icons: ["house", "hearts"], answer: "بيتي جنتي", hints: ["عن حب الوطن", "المنزل عزيز", "راحة البال في البيت"], category: "proverbs" },
        { icons: ["ear", "ear", "speaking-head"], answer: "من كثر كلامه قل احترامه", hints: ["عن قلة الكلام", "الصمت أفضل أحياناً", "كثرة الكلام مذمومة"], category: "wisdom" },
        { icons: ["camel", "wind"], answer: "العجلة من الشيطان", hints: ["عن التأني", "لا تستعجل", "التسرع مذموم"], category: "religion" },
        { icons: ["handshake", "muscle"], answer: "الاتحاد قوة", hints: ["عن التعاون", "معاً أقوى", "الجماعة أفضل"], category: "wisdom" },
        { icons: ["smile", "pill"], answer: "الابتسامة أفضل دواء", hints: ["عن السعادة", "الضحك مفيد", "الابتسامة تشفي"], category: "wisdom" },
        { icons: ["crescent-moon", "glowing-star"], answer: "ليلة القدر خير من ألف شهر", hints: ["آية قرآنية", "عن شهر رمضان", "ليلة مباركة"], category: "religion" },
        { icons: ["lion", "sheep"], answer: "الذئب لا يرعى الغنم", hints: ["عن الثقة في غير موضعها", "لا تأتمن عدوك", "الطبع يغلب"], category: "proverbs" },
        { icons: ["muscle", "brain"], answer: "العقل السليم في الجسم السليم", hints: ["عن الصحة", "الرياضة مهمة", "العقل والجسد متصلان"], category: "wisdom" },
        { icons: ["wave", "fish"], answer: "السمكة الكبيرة تأكل الصغيرة", hints: ["عن قانون الغاب", "القوي يغلب", "الحياة صعبة"], category: "proverbs" },
        { icons: ["fire", "wind"], answer: "لا دخان بلا نار", hints: ["كل شيء له سبب", "الإشاعات لها أصل", "هناك سبب دائماً"], category: "proverbs" },
        { icons: ["eyes", "anatomical-heart"], answer: "العين بصيرة واليد قصيرة", hints: ["عن العجز", "أرى ولا أستطيع", "القدرة محدودة"], category: "proverbs" },
        { icons: ["eye", "camel"], answer: "عين الحسود فيها عود", hints: ["عن الحسد", "العين تؤذي", "دعاء ضد الحاسد"], category: "proverbs" },
        { icons: ["house", "fire", "house"], answer: "الجار قبل الدار", hints: ["أهمية الجيران", "اختر جارك قبل بيتك", "مثل عن الجيرة"], category: "proverbs" },
        { icons: ["money-bag", "wave-hand"], answer: "الفلوس تجيب العروس", hints: ["المال مهم للزواج", "مثل عن الزواج", "الغنى يسهل الأمور"], category: "proverbs" },
        { icons: ["palm-tree", "wind"], answer: "اللي ما تحركه الريح ثقيل", hints: ["عن الثبات", "القوي لا يتأثر", "مثل عن الصمود"], category: "proverbs" },
        { icons: ["dog", "bone"], answer: "الكلب يعرف ربعه", hints: ["عن معرفة الأصدقاء", "الوفاء للأهل", "مثل عن الولاء"], category: "proverbs" },
        { icons: ["crescent-moon", "star"], answer: "كل ليلة ولها صبح", hints: ["الفرج قادم", "بعد الليل نهار", "عن الأمل"], category: "wisdom" },
        { icons: ["horse", "wind"], answer: "الخيل من خيّالها", hints: ["القائد يصنع الفرق", "الفارس مهم", "عن القيادة"], category: "wisdom" },
        { icons: ["falcon", "eyes"], answer: "الصقر ما ياكل إلا حي", hints: ["الكرامة في العمل", "لا يأخذ بلا جهد", "عن العزة"], category: "wisdom" },
        { icons: ["desert", "rain"], answer: "المطر ما ينفع في البر اليابس", hints: ["الشيء في غير موضعه", "لا فائدة", "عن الجدوى"], category: "proverbs" },
        { icons: ["ear", "mouth"], answer: "اللي يسمع يخرف", hints: ["كثرة السماع", "الإشاعات", "لا تصدق كل شيء"], category: "proverbs" },
        { icons: ["camel-loaded", "walking"], answer: "صاحب البعير أدرى بمناخه", hints: ["صاحب الشيء أعلم به", "الخبرة مهمة", "اسأل أهل الاختصاص"], category: "proverbs" },
        { icons: ["fire", "bread"], answer: "اللي يبي الحب يصبر على التعب", hints: ["النجاح يحتاج صبر", "لا راحة بلا تعب", "عن الكفاح"], category: "wisdom" },
        { icons: ["wave-hand", "house"], answer: "بيت السكوت ما يخرب", hints: ["الصمت حكمة", "قلة الكلام سلامة", "عن السكوت"], category: "wisdom" },
        { icons: ["sheep", "sheep"], answer: "الغنم ما تنطح إلا من روسها", hints: ["المشاكل من الداخل", "الخلاف بين الأقارب", "عن الفتنة"], category: "proverbs" },
        { icons: ["sun", "palm-tree"], answer: "كل شي بوقته حلو", hints: ["التوقيت مهم", "لكل شيء وقت", "عن الصبر"], category: "wisdom" },
        { icons: ["diamond", "wave-hand"], answer: "اللي في يده الذهب ما يخاف", hints: ["المال يعطي أمان", "الغني مطمئن", "عن الثراء"], category: "proverbs" },
        { icons: ["camel", "camel", "eye"], answer: "الإبل على كثرها ما تسد عين الحسود", hints: ["الحسود لا يشبع", "مهما أعطيته", "عن الحسد"], category: "proverbs" },
        { icons: ["father-son", "tree"], answer: "اللي ما عنده كبير يشتري له كبير", hints: ["أهمية الكبار", "الحكمة من الشيوخ", "احترام الكبير"], category: "proverbs" },
        { icons: ["chicken", "egg", "money-bag"], answer: "الدجاجة اللي تبيض ذهب لا تذبحها", hints: ["لا تضحي بمصدر رزقك", "الصبر على المكاسب", "عن الحكمة"], category: "wisdom" },
        { icons: ["falcon", "arrow-down", "falcon"], answer: "الصقر لو يوقع يبقى صقر", hints: ["الأصل يبقى", "الشريف شريف", "عن الأصالة"], category: "wisdom" }
    ],
    medium: [
        { icons: ["elephant", "brain", "thought-bubble"], answer: "ذاكرة الفيل", hints: ["عن قوة الذاكرة", "لا ينسى أبداً", "حيوان لا ينسى"], category: "proverbs" },
        { icons: ["rainbow", "umbrella-rain"], answer: "بعد المطر تطلع الشمس", hints: ["عن الأمل", "الفرج قادم", "بعد الضيق فرج"], category: "wisdom" },
        { icons: ["ant", "mountain"], answer: "النملة تحرك الجبل", hints: ["عن المثابرة", "الإصرار يصنع المعجزات", "لا تستهن بالصغير"], category: "wisdom" },
        { icons: ["speaking-head", "diamond", "shush", "gold-medal"], answer: "الكلام من فضة والسكوت من ذهب", hints: ["عن الصمت والكلام", "أحياناً الصمت أفضل", "مثل عربي شهير"], category: "wisdom" },
        { icons: ["walking", "turtle", "trophy"], answer: "من سار على الدرب وصل", hints: ["عن الصبر", "المثابرة تؤدي للنجاح", "استمر في طريقك"], category: "wisdom" },
        { icons: ["rose", "leaf"], answer: "كل وردة ولها شوكة", hints: ["لكل جميل عيب", "الحياة فيها حلو ومر", "لا شيء كامل"], category: "proverbs" },
        { icons: ["silhouette", "mirror"], answer: "اللي ما يعرفك ما يثمنك", hints: ["قيمتك عند من يعرفك", "الجاهل لا يقدر", "القيمة في المعرفة"], category: "wisdom" },
        { icons: ["grapes", "fox"], answer: "العنب الذي لا تناله اليد حامض", hints: ["قصة الثعلب والعنب", "التبرير للفشل", "ما لا تستطيعه تزهد فيه"], category: "proverbs" },
        { icons: ["door", "hammer"], answer: "الباب اللي يجيك منه ريح سده واستريح", hints: ["تجنب المشاكل", "أغلق باب المتاعب", "الوقاية خير"], category: "proverbs" },
        { icons: ["elderly", "books", "baby"], answer: "اسأل مجرب ولا تسأل طبيب", hints: ["الخبرة أهم", "التجربة خير معلم", "المجرب أعلم"], category: "proverbs" },
        { icons: ["wheat", "bird"], answer: "إذا طاح الجمل كثرت سكاكينه", hints: ["عندما يضعف القوي", "الناس تهجم على الضعيف", "كثرة الطامعين"], category: "proverbs" },
        { icons: ["eye", "warning", "open-hands"], answer: "من راقب الناس مات هماً", hints: ["لا تشغل بالك بالآخرين", "التطفل مذموم", "عش حياتك"], category: "wisdom" },
        { icons: ["crescent-moon", "star", "flashlight"], answer: "اطلب العلى واترك الدنى", hints: ["اسعَ للأفضل", "الطموح مطلوب", "لا ترضَ بالقليل"], category: "wisdom" },
        { icons: ["coin", "refresh", "coin"], answer: "الدنيا دولاب", hints: ["الأيام دول", "الحال يتغير", "لا شيء يدوم"], category: "wisdom" },
        { icons: ["broken-heart", "bandage", "clock"], answer: "الزمن كفيل بكل شيء", hints: ["الوقت يشفي", "الصبر جميل", "كل شيء يمر"], category: "wisdom" },
        { icons: ["dog", "bone", "house"], answer: "الكلب في بيته سبع", hints: ["القوة في موطنك", "الإنسان قوي في أرضه", "الشجاعة في الوطن"], category: "proverbs" },
        { icons: ["wave", "wave", "ship"], answer: "البحر ما يكدره زود العيون", hints: ["الكبير لا يتأثر بالصغير", "لا تؤثر على العظيم", "الحسد لا يضر الواثق"], category: "proverbs" },
        { icons: ["theater-masks", "smile", "cry"], answer: "الدنيا مسرح كبير", hints: ["الحياة تمثيل", "كلنا نلعب أدواراً", "شكسبير قالها"], category: "wisdom" },
        { icons: ["open-book", "sparkles", "brain"], answer: "القراءة غذاء الروح", hints: ["أهمية القراءة", "الكتب مفيدة", "اقرأ تستفد"], category: "wisdom" },
        { icons: ["seedling", "water-drop", "sun", "tree"], answer: "ازرع ولو في الصخر", hints: ["لا تيأس", "حاول دائماً", "الأمل موجود"], category: "wisdom" },
        { icons: ["wave", "swimmer"], answer: "اللي يخوض البحر ما يخاف من المطر", hints: ["الشجاع لا يخاف", "من جرب الصعب", "عن الجرأة"], category: "proverbs" },
        { icons: ["camel-loaded", "nose"], answer: "البعير ما يشوف عوجة رقبته", hints: ["الإنسان لا يرى عيوبه", "انتقاد الغير", "عن النقد الذاتي"], category: "proverbs" },
        { icons: ["palm-tree", "axe"], answer: "اللي يزرع الشوك ما يحصد تمر", hints: ["كما تزرع تحصد", "النتيجة من العمل", "عن الجزاء"], category: "wisdom" },
        { icons: ["lion", "puppy"], answer: "ابن الأسد أسد", hints: ["الفرع من الأصل", "الابن مثل أبيه", "عن الوراثة"], category: "proverbs" },
        { icons: ["water-drop", "milk"], answer: "الماي ما يصير لبن", hints: ["الشيء لا يتغير", "الأصل ثابت", "عن الطبيعة"], category: "proverbs" },
        { icons: ["house", "eye", "heart"], answer: "بيتك يا اللي تحبه ولو كان خيمة", hints: ["حب الوطن", "البيت عزيز", "عن الانتماء"], category: "proverbs" },
        { icons: ["horse-running", "wind", "fog"], answer: "الخيل إن غابت طلع غبارها", hints: ["الأثر يبقى", "السمعة تدوم", "عن الذكرى"], category: "proverbs" },
        { icons: ["tooth", "plate"], answer: "اللي ياكل على ضرسه ينفع نفسه", hints: ["الاعتماد على النفس", "اعمل بيدك", "عن الاستقلالية"], category: "wisdom" },
        { icons: ["wolf", "sheep", "shield"], answer: "ذيب يحرس غنم", hints: ["وضع الخائن أميناً", "الثقة في غير موضعها", "عن الخيانة"], category: "proverbs" },
        { icons: ["wheat", "farmer", "plate"], answer: "ازرع كل يوم تاكل كل يوم", hints: ["العمل المستمر", "الاستمرارية", "عن الاجتهاد"], category: "wisdom" },
        { icons: ["chicken", "hand", "falcon", "cloud"], answer: "دجاجة في اليد ولا صقر في السما", hints: ["القناعة بالموجود", "المضمون أفضل", "عن القناعة"], category: "proverbs" },
        { icons: ["wave", "ship", "pilot"], answer: "البحر له ناس وأهل", hints: ["كل شيء له أهله", "الخبرة مطلوبة", "عن التخصص"], category: "proverbs" },
        { icons: ["fried-egg", "fire", "x-mark"], answer: "اللي ما يعرف يطبخ يحرق الزاد", hints: ["الجاهل يفسد", "العلم ضروري", "عن المعرفة"], category: "proverbs" },
        { icons: ["palm-tree", "palm-tree", "muscle"], answer: "النخلة ما تبرك إلا على ليفها", hints: ["الاعتماد على الأهل", "القوة من الداخل", "عن الأصل"], category: "proverbs" },
        { icons: ["wind", "camel-loaded", "magnifier"], answer: "إذا هب الهبوب تعرف الركايب", hints: ["الشدة تكشف المعادن", "الأزمات تبين الحقيقة", "عن الاختبار"], category: "wisdom" },
        { icons: ["elderly", "open-book", "doctor"], answer: "اسأل مجرب ولا تسأل حكيم", hints: ["التجربة أهم", "العملي أفضل", "عن الخبرة"], category: "proverbs" },
        { icons: ["wood-log", "wind", "fire"], answer: "كل عود فيه دخان", hints: ["لكل شيء عيب", "لا أحد كامل", "مثل خليجي"], category: "proverbs" },
        { icons: ["snake", "milk", "skull-crossbones"], answer: "تحلب الثعبان سم", hints: ["الشرير يبقى شرير", "لا خير من السيء", "عن الطبع"], category: "proverbs" },
        { icons: ["father-son", "muscle", "cry"], answer: "العز للرجال والذل للرجال", hints: ["الرجل يمر بكل شيء", "الأيام دول", "عن تقلبات الحياة"], category: "wisdom" },
        { icons: ["camel", "running", "prohibited"], answer: "اللي ما يعرف الصقر يشويه", hints: ["عن الجهل بالقيمة", "الصقر طير ثمين", "مثل خليجي مشهور"], category: "proverbs" }
    ],
    hard: [
        { icons: ["castle", "brick", "silhouette"], answer: "من حفر حفرة لأخيه وقع فيها", hints: ["الكيد يرتد", "من يضر غيره يتضرر", "الظلم مرتد"], category: "wisdom" },
        { icons: ["sunrise", "mountain-sunrise", "refresh"], answer: "دوام الحال من المحال", hints: ["لا شيء يدوم", "التغيير سنة الحياة", "الأيام تتبدل"], category: "wisdom" },
        { icons: ["theater-masks", "circus-tent", "globe"], answer: "الدنيا ساعة فاجعلها طاعة", hints: ["الحياة قصيرة", "استغل وقتك", "حكمة إسلامية"], category: "religion" },
        { icons: ["scales", "lion", "ant"], answer: "إذا أردت أن تطاع فأمر بما يستطاع", hints: ["القيادة الحكيمة", "لا تكلف فوق الطاقة", "الأمر الممكن"], category: "wisdom" },
        { icons: ["sword", "shield", "scroll"], answer: "السيف أصدق إنباء من الكتب", hints: ["بيت شعر للمتنبي", "الفعل أقوى من الكلام", "التجربة خير برهان"], category: "poetry" },
        { icons: ["crescent-moon", "telescope", "glowing-star", "target"], answer: "من لم يكن له بداية محرقة لم تكن له نهاية مشرقة", hints: ["البدايات الصعبة", "الكفاح يؤدي للنجاح", "لا مجد بلا تعب"], category: "wisdom" },
        { icons: ["landmark", "crown", "skull"], answer: "كم من عظيم قضى وهو صغير وكم من صغير عاش وهو كبير", hints: ["القيمة ليست بالعمر", "العظمة بالأفعال", "الموت لا يفرق"], category: "wisdom" },
        { icons: ["wave", "sailboat", "compass", "x-mark"], answer: "البحر طريق من لا طريق له", hints: ["خيار الضعيف", "الهجرة والمخاطرة", "اللجوء للمجهول"], category: "wisdom" },
        { icons: ["falcon", "nest", "mountain-sunrise"], answer: "لا تحسبن المجد تمراً أنت آكله لن تبلغ المجد حتى تلعق الصبرا", hints: ["شعر عربي", "المجد يحتاج صبر", "النجاح صعب"], category: "poetry" },
        { icons: ["hourglass", "diamond", "sunrise"], answer: "إضاعة الوقت أشد من الموت", hints: ["قيمة الوقت", "حكمة إسلامية", "الوقت أغلى شيء"], category: "religion" },
        { icons: ["target", "bow-arrow", "crescent-moon"], answer: "من جد وجد ومن زرع حصد", hints: ["الجهد يؤتي ثماره", "اعمل تجد", "النتيجة من السعي"], category: "wisdom" },
        { icons: ["lion", "crown", "headstone"], answer: "عش عزيزاً أو مت وأنت كريم", hints: ["الكرامة قبل كل شيء", "العزة في الحياة والموت", "شعر حماسي"], category: "poetry" },
        { icons: ["prayer-beads", "mosque", "crescent-moon", "sparkles"], answer: "رب اشرح لي صدري ويسر لي أمري", hints: ["دعاء نبي الله موسى", "طلب التيسير من الله", "آية قرآنية"], category: "religion" },
        { icons: ["crossed-swords", "castle", "fire", "wind"], answer: "الحرب خدعة", hints: ["حديث نبوي", "المكر في الحرب", "الذكاء العسكري"], category: "religion" },
        { icons: ["rose", "fire", "wind", "hourglass"], answer: "كل من عليها فان ويبقى وجه ربك ذو الجلال والإكرام", hints: ["آية قرآنية", "الفناء للجميع", "البقاء لله وحده"], category: "religion" },
        { icons: ["butterfly", "cherry-blossom", "fallen-leaf", "snowflake"], answer: "لكل زمان دولة ورجال", hints: ["التغيير سنة", "الأوقات تتبدل", "لكل عصر أبطاله"], category: "wisdom" },
        { icons: ["mountain", "wave", "tornado", "fire"], answer: "من صبر ظفر", hints: ["الصبر مفتاح النصر", "انتظر وستنتصر", "مثل عن الصبر"], category: "wisdom" },
        { icons: ["eye", "crystal-ball", "sunrise", "mountain-sunrise"], answer: "رب ضارة نافعة", hints: ["الشر قد يأتي بخير", "المصائب فيها فوائد", "انظر للجانب الإيجابي"], category: "proverbs" },
        { icons: ["theater-masks", "silhouette", "mirror", "silhouettes"], answer: "الناس أعداء ما جهلوا", hints: ["الجهل سبب العداوة", "حكمة علي بن أبي طالب", "العلم يزيل العداوة"], category: "wisdom" },
        { icons: ["scroll", "writing-hand", "blood-drop", "muscle"], answer: "ما حك جلدك مثل ظفرك فتول أنت جميع أمرك", hints: ["اعتمد على نفسك", "لا أحد يهتم بأمرك مثلك", "شعر عربي قديم"], category: "poetry" },
        { icons: ["desert", "sunrise", "hourglass", "sweat"], answer: "الصبر مفتاح الفرج واللي يستعجل يتعب", hints: ["حكمة خليجية", "التأني مطلوب", "عن الصبر والنتائج"], category: "wisdom" },
        { icons: ["ship", "mountain", "target"], answer: "اللي ما يركب المراكب ما يجي له مراده", hints: ["المخاطرة مطلوبة", "لا نجاح بلا مغامرة", "عن الشجاعة"], category: "proverbs" },
        { icons: ["falcon", "crown", "hand", "meat"], answer: "الصقر لو جاع ما ياكل إلا من كسب يده", hints: ["العزة في العمل", "الكرامة أولاً", "عن الشرف"], category: "wisdom" },
        { icons: ["turban-man", "hijab-woman", "x-mark", "man"], answer: "ما كل من لبس العقال صار رجال", hints: ["المظهر لا يكفي", "الرجولة بالأفعال", "عن الحقيقة"], category: "proverbs" },
        { icons: ["luggage", "house", "cry"], answer: "الغريب لو كرموه غريب", hints: ["الغربة صعبة", "الوطن لا يعوض", "عن الاغتراب"], category: "proverbs" },
        { icons: ["oyster", "diamond", "swimmer"], answer: "اللي يبي اللؤلؤ يغوص له", hints: ["النفيس يحتاج جهد", "لا شيء بسهولة", "عن الكفاح"], category: "wisdom" },
        { icons: ["railway", "railway", "dizzy"], answer: "كثر الدروب تضيع المسافر", hints: ["كثرة الخيارات تحير", "ركز على هدف واحد", "عن التركيز"], category: "wisdom" },
        { icons: ["hand", "lion", "crown"], answer: "ما يحك جلدك مثل ظفرك", hints: ["اعتمد على نفسك", "أنت أدرى بأمورك", "عن الاستقلالية"], category: "poetry" },
        { icons: ["desert", "crown", "crown", "x-mark"], answer: "البر ما يحتمل اثنين من ربعه", hints: ["القيادة لواحد", "لا يصلح رئيسان", "عن الزعامة"], category: "proverbs" },
        { icons: ["falcon", "wing", "airplane"], answer: "الطير لو طار ما طار إلا بجناحه", hints: ["لا تعتمد على غيرك", "قوتك منك", "عن الاستقلال"], category: "wisdom" },
        { icons: ["house", "wheat", "fire", "x-mark"], answer: "اللي بيته من قش ما يحارب بالنار", hints: ["اعرف قدرك", "لا تتحدى بما يضرك", "عن الحكمة"], category: "wisdom" },
        { icons: ["snake", "egg", "snake"], answer: "الحية ما تلد إلا حية", hints: ["الأصل يورث", "ابن الشرير شرير", "عن الوراثة"], category: "proverbs" },
        { icons: ["wave", "relieved", "sailboat", "x-mark"], answer: "البحار الهادي ما يصنع بحار ماهر", hints: ["الصعوبات تصنع الرجال", "التحديات ضرورية", "عن التجربة"], category: "wisdom" },
        { icons: ["sparkles", "magnifier", "diamond", "x-mark"], answer: "ما كل ما يلمع ذهب", hints: ["لا تنخدع بالمظاهر", "الحقيقة مختلفة", "عن التمييز"], category: "wisdom" },
        { icons: ["camel-loaded", "eye", "arrow-left"], answer: "عين البعير ما تشوف إلا قدامها", hints: ["النظرة المحدودة", "الرؤية الضيقة", "عن ضيق الأفق"], category: "proverbs" },
        { icons: ["falcon", "cloud", "arrow-up", "anxious"], answer: "الصقر يرتفع فوق السحاب وقت الضيق", hints: ["الشجاع يظهر بالشدة", "القوي في الأزمات", "عن العزيمة"], category: "wisdom" },
        { icons: ["palm-tree", "water-drop", "sun", "grapes"], answer: "النخلة ما تثمر إلا إذا رويتها", hints: ["العناية تأتي بالثمار", "الاهتمام مطلوب", "عن الرعاية"], category: "proverbs" },
        { icons: ["running", "wind", "trophy", "x-mark"], answer: "اللي يسابق الريح يتعب حاله", hints: ["لا تتحدى المستحيل", "اعرف حدودك", "عن الواقعية"], category: "wisdom" },
        { icons: ["crown", "bed", "broom"], answer: "الشيخ شيخ لو نام على حصير", hints: ["القيمة بالجوهر", "المكانة ليست بالمال", "عن الأصالة"], category: "wisdom" },
        { icons: ["muscle", "plate", "x-mark", "angry"], answer: "اللي له عز ما يذل ولو جاع", hints: ["الكرامة لا تباع", "العزة فوق كل شيء", "عن الشرف"], category: "wisdom" }
    ]
};

export function filterByCategory(questions, category) {
    if (!category || category === 'all') return questions;
    return questions.filter(q => q.category === category);
}
